---
name: Docker Build & Push
description: |
  Build the application's Dockerfile, and push it to the given registry.

  Some notes:
  - Will fallback to docker hub registry (if none is provided)
  - Image name will default to the current repository name
  - Tag will default to the current branch
inputs:
  container-registry:
    description: Container registry endpoint (fallback to Docker Hub)
    required: false
  container-registry-username:
    description: Container registry username
    required: true
  container-registry-password:
    description: Container registry password
    required: true
  github-access-token:
    description: GitHub access token (GITHUB_TOKEN)
    required: true
  image:
    description: Image name (fallback to repository name)
    required: false
  tags:
    description: Image tags (fallback to branch name)
    required: false
  platforms:
    description: List of platforms (architectures, comma separated, defaults to `linux/amd64`)
    required: false
  target:
    description: Docker target (build-stage) you want to build.
    required: false
outputs:
  digest:
    description: Result image digest
    value: ${{ steps.build.outputs.digest }}
  manifest:
    description: Image manifest (registry + image + tag)
    value: ${{ env.tags }}

runs:
  using: composite
  steps:
    # Prepare
    - name: Prepare environment
      shell: bash
      run: |
        registry=${{ inputs.container-registry || 'docker.io' }}
        image=`basename ${{ inputs.image || github.repository }}`

        echo "registry=${registry}" >> "$GITHUB_ENV"
        echo "tags=`echo '${{ inputs.tags || github.ref_name }}' | \
          sed "s#/#_#g;s#[^,]*#${registry}/${image}:&#g"`" >> "$GITHUB_ENV"
        echo "platforms=${{ inputs.platforms || 'linux/amd64' }}" >> "$GITHUB_ENV"
        echo "timestamp=`date +'%Y-%m-%dT%H:%M:%S'`" >> "$GITHUB_ENV"
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # Authenticate
    - name: Login to GitHub registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-access-token }}
    - name: Login to custom registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-password }}
    # Build
    - name: Build and push
      uses: docker/build-push-action@v6
      id: build
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ env.platforms }}
        push: true
        tags: ${{ env.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: ${{ inputs.target }}
        build-args: |
          BUILD_COMMIT=${{ github.sha }}
          BUILD_NUMBER=${{ github.run_number }}
          BUILD_TIMESTAMP=${{ env.timestamp }}
